-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 13:08:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TrackCommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrackCommerce
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `TrackCommerce`;
CREATE DATABASE IF NOT EXISTS `TrackCommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `TrackCommerce` ;

-- -----------------------------------------------------
-- Table `TrackCommerce`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Permissao` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Permissao` (
  `id_permissao` INT NOT NULL AUTO_INCREMENT,
  `nome_permissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_permissao`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Cargo_Permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Cargo_Permissao` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Cargo_Permissao` (
  `fk_cargo` INT NOT NULL,
  `fk_permissao` INT NOT NULL,
  PRIMARY KEY (`fk_cargo`, `fk_permissao`),
  CONSTRAINT `fk_cp_cargo`
    FOREIGN KEY (`fk_cargo`)
    REFERENCES `TrackCommerce`.`Cargo` (`id_cargo`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cp_permissao`
    FOREIGN KEY (`fk_permissao`)
    REFERENCES `TrackCommerce`.`Permissao` (`id_permissao`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_cp_permissao` ON `TrackCommerce`.`Cargo_Permissao` (`fk_permissao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Componentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Componentes` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Componentes` (
  `id_componente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `dt_atribuicao` DATETIME NOT NULL,
  PRIMARY KEY (`id_componente`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `estado` CHAR(2) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `fk_endereco` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa`),
  CONSTRAINT `fk_empresa_endereco`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `TrackCommerce`.`Endereco` (`id_endereco`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `uq_empresa_cnpj` ON `TrackCommerce`.`Empresa` (`cnpj` ASC) VISIBLE;

CREATE INDEX `fk_empresa_endereco` ON `TrackCommerce`.`Empresa` (`fk_endereco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Instancias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Instancias` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Instancias` (
  `id_instancia` INT NOT NULL AUTO_INCREMENT,
  `fk_empresa` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200),
  `identificador` VARCHAR(500) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_instancia`),
  CONSTRAINT `fk_instancia_empresa`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `TrackCommerce`.`Empresa` (`id_empresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `uq_instancia_identificador` ON `TrackCommerce`.`Instancias` (`identificador` ASC) VISIBLE;

CREATE INDEX `fk_instancia_empresa` ON `TrackCommerce`.`Instancias` (`fk_empresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `celular` CHAR(11) NULL DEFAULT NULL,
  `fk_empresa` INT NOT NULL,
  `fk_cargo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_cargo`
    FOREIGN KEY (`fk_cargo`)
    REFERENCES `TrackCommerce`.`Cargo` (`id_cargo`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `TrackCommerce`.`Empresa` (`id_empresa`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `uq_usuario_email` ON `TrackCommerce`.`Usuario` (`email` ASC) VISIBLE;

CREATE INDEX `fk_usuario_empresa` ON `TrackCommerce`.`Usuario` (`fk_empresa` ASC) VISIBLE;

CREATE INDEX `fk_usuario_cargo` ON `TrackCommerce`.`Usuario` (`fk_cargo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Parametros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Parametros` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Parametros` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `unidade_medida` VARCHAR(15) NOT NULL,
  `dt_atribuicao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Componentes_id_componente` INT NOT NULL,
  PRIMARY KEY (`id_parametro`),
  CONSTRAINT `fk_Parametros_Componentes1`
    FOREIGN KEY (`Componentes_id_componente`)
    REFERENCES `TrackCommerce`.`Componentes` (`id_componente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Parametros_Componentes1_idx` ON `TrackCommerce`.`Parametros` (`Componentes_id_componente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Parametros_Alertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Parametros_Alertas` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Parametros_Alertas` (
  `id_parametro_alerta` INT NOT NULL AUTO_INCREMENT,
  `alerta_moderado` DOUBLE NOT NULL,
  `alerta_critico` DOUBLE NOT NULL,
  `dt_edicao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_parametro` INT NOT NULL,
  PRIMARY KEY (`id_parametro_alerta`),
  CONSTRAINT `fk_Parametros_Alertas_Parametros1`
    FOREIGN KEY (`fk_parametro`)
    REFERENCES `TrackCommerce`.`Parametros` (`id_parametro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Parametros_Alertas_Parametros1_idx` ON `TrackCommerce`.`Parametros_Alertas` (`fk_parametro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`Instancias_Componentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`Instancias_Componentes` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`Instancias_Componentes` (
  `id_instancia_componente` INT NOT NULL,
  `fk_instancia` INT NOT NULL,
  `fk_componentes` INT NOT NULL,
  `fk_parametros_alertas` INT NOT NULL,
  `Status` TINYINT NOT NULL DEFAULT 1,
  `dt_edicao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_instancia_componente`, `fk_instancia`, `fk_componentes`, `fk_parametros_alertas`),
  CONSTRAINT `fk_Instancias_has_Componentes_Instancias1`
    FOREIGN KEY (`fk_instancia`)
    REFERENCES `TrackCommerce`.`Instancias` (`id_instancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instancias_has_Componentes_Componentes1`
    FOREIGN KEY (`fk_componentes`)
    REFERENCES `TrackCommerce`.`Componentes` (`id_componente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instancias_Componentes_Parametros_Alertas1`
    FOREIGN KEY (`fk_parametros_alertas`)
    REFERENCES `TrackCommerce`.`Parametros_Alertas` (`id_parametro_alerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Instancias_has_Componentes_Componentes1_idx` ON `TrackCommerce`.`Instancias_Componentes` (`fk_componentes` ASC) VISIBLE;

CREATE INDEX `fk_Instancias_has_Componentes_Instancias1_idx` ON `TrackCommerce`.`Instancias_Componentes` (`fk_instancia` ASC) VISIBLE;

CREATE INDEX `fk_Instancias_Componentes_Parametros_Alertas1_idx` ON `TrackCommerce`.`Instancias_Componentes` (`fk_parametros_alertas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TrackCommerce`.`ApiJira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCommerce`.`ApiJira` ;

CREATE TABLE IF NOT EXISTS `TrackCommerce`.`ApiJira` (
  `id_api_jira` INT NOT NULL,
  `codigo_api` VARCHAR(500) NOT NULL,
  `fk_empresa` INT NOT NULL,
  PRIMARY KEY (`id_api_jira`),
  CONSTRAINT `fk_ApiJira_Empresa1`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `TrackCommerce`.`Empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ApiJira_Empresa1_idx` ON `TrackCommerce`.`ApiJira` (`fk_empresa` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
